### ISSUE TITLE
フロントをつくる

### ISSUE THREAD

**Issue by kshiva1126** [kshiva1126/kicky_wiki#1]
デザインに基づいてつくる
デザイン画像は下記の通り
- TOP
![Kicky-WIKI（トップ）](https://user-images.githubusercontent.com/42695879/58744144-1fbe8680-8479-11e9-8c61-1d4cab5b287d.png)
- 詳細
![Kicky-WIKI（詳細）](https://user-images.githubusercontent.com/42695879/58744152-382ea100-8479-11e9-9d70-f30b039212ee.png)
- 登録・編集
![Kicky-WIKI（登録・編集）](https://user-images.githubusercontent.com/42695879/58744155-4b417100-8479-11e9-8042-2fe9f5813e3e.png)

**Comment by yusukeito58** [comment]
@kshiva1126 
一旦PR、サイトイメージ案が出次第詳細を作成予定。

問題なければ完了してください😊
